name: Test

on:
    push:
        branches:
            - main
        paths:
            - "utils/**"
            - "*.jl"
            - "*.toml"

    workflow_dispatch:

jobs:
    test:
        uses: ./.github/workflows/ReusableTest.yml
        with:
            os: ${{ matrix.os }}
            version: ${{ matrix.version }}
            arch: ${{ matrix.arch }}
            allow_failure: ${{ matrix.allow_failure }}
        strategy:
            fail-fast: false
            matrix:
                version:
                    - "1"
                os:
                    - ubuntu-latest
                    - macOS-latest
                    - windows-latest
                arch:
                    - x64
                allow_failure: [false]
